name: Release from Master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
