name: Release from Staging

on:
  push:
    branches: [ staging ]

jobs:
  production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Merge staging -> production
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: production 
          github_token: ${{ github.token }}